SELECT 
    B.FOOD_TYPE, 
    A.REST_ID, 
    A.REST_NAME, 
    B.FAVORITES 
FROM REST_INFO A 
JOIN (SELECT 
        FOOD_TYPE, 
        MAX(FAVORITES) AS FAVORITES 
      FROM REST_INFO 
      GROUP BY FOOD_TYPE) B 
USING (FAVORITES)
GROUP BY FOOD_TYPE 
ORDER BY FOOD_TYPE DESC

